# Generated by Django 5.0.1 on 2026-02-16 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('nom', models.CharField(help_text='Ex: 2025-2026', max_length=50, unique=True, verbose_name='nom')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('systeme_evaluation', models.CharField(choices=[('TRIMESTRE', 'Trimestres'), ('SEMESTRE', 'Semestres')], default='TRIMESTRE', max_length=20, verbose_name="système d'évaluation")),
                ('trimestre1_debut', models.DateField(blank=True, null=True, verbose_name='trimestre 1 - début')),
                ('trimestre1_fin', models.DateField(blank=True, null=True, verbose_name='trimestre 1 - fin')),
                ('trimestre2_debut', models.DateField(blank=True, null=True, verbose_name='trimestre 2 - début')),
                ('trimestre2_fin', models.DateField(blank=True, null=True, verbose_name='trimestre 2 - fin')),
                ('trimestre3_debut', models.DateField(blank=True, null=True, verbose_name='trimestre 3 - début')),
                ('trimestre3_fin', models.DateField(blank=True, null=True, verbose_name='trimestre 3 - fin')),
                ('semestre1_debut', models.DateField(blank=True, null=True, verbose_name='semestre 1 - début')),
                ('semestre1_fin', models.DateField(blank=True, null=True, verbose_name='semestre 1 - fin')),
                ('semestre2_debut', models.DateField(blank=True, null=True, verbose_name='semestre 2 - début')),
                ('semestre2_fin', models.DateField(blank=True, null=True, verbose_name='semestre 2 - fin')),
                ('est_active', models.BooleanField(default=False, help_text='Une seule année peut être active à la fois', verbose_name='année active')),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelNonEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('fonction', models.CharField(choices=[('DIRECTEUR', 'Directeur/Directrice'), ('SECRETAIRE', 'Secrétaire'), ('BIBLIO', 'Bibliothécaire'), ('SURVEILLANT', 'Surveillant'), ('INTENDANT', 'Intendant'), ('GARDIEN', 'Gardien'), ('ENTRETIEN', "Agent d'entretien"), ('TECH_INFO', 'Technicien informatique')], max_length=20, verbose_name='fonction')),
                ('numero_cnss', models.CharField(blank=True, max_length=50, verbose_name='numéro CNSS')),
                ('date_embauche', models.DateField(verbose_name="date d'embauche")),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='date de départ')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'personnel non enseignant',
                'verbose_name_plural': 'personnel non enseignant',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('numero', models.CharField(help_text='Ex: A101, LAB-01', max_length=20, unique=True, verbose_name='numéro')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('type_salle', models.CharField(choices=[('CLASSE', 'Salle de classe'), ('LABO', 'Laboratoire'), ('INFO', 'Salle informatique'), ('BIBLIO', 'Bibliothèque'), ('CONF', 'Salle de conférence'), ('SPORT', 'Salle de sport')], default='CLASSE', max_length=10, verbose_name='type')),
                ('capacite', models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacité')),
                ('batiment', models.CharField(blank=True, max_length=50, verbose_name='bâtiment')),
                ('etage', models.CharField(blank=True, max_length=20, verbose_name='étage')),
                ('a_projecteur', models.BooleanField(default=False, verbose_name='projecteur')),
                ('a_climatisation', models.BooleanField(default=False, verbose_name='climatisation')),
                ('a_tableau_numerique', models.BooleanField(default=False, verbose_name='tableau numérique')),
                ('nombre_ordinateurs', models.PositiveIntegerField(default=0, verbose_name="nombre d'ordinateurs")),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'salle',
                'verbose_name_plural': 'salles',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="date d'inscription")),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=15, verbose_name='statut')),
                ('acte_naissance', models.FileField(blank=True, null=True, upload_to='inscriptions/actes/%Y/', verbose_name='acte de naissance')),
                ('certificat_scolarite_precedent', models.FileField(blank=True, null=True, upload_to='inscriptions/certificats/%Y/', verbose_name='certificat scolarité précédent')),
                ('photo_identite', models.ImageField(blank=True, null=True, upload_to='inscriptions/photos/%Y/', verbose_name="photo d'identité")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='administration.anneescolaire', verbose_name='année scolaire')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
