# Generated by Django 5.0.1 on 2026-02-16 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('authentication', '0001_initial'),
        ('pedagogie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='pedagogie.classe', verbose_name='classe'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='authentication.eleveprofile', verbose_name='élève'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees', to=settings.AUTH_USER_MODEL, verbose_name='validée par'),
        ),
        migrations.AddField(
            model_name='personnelnonenseignant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('eleve', 'annee_scolaire')},
        ),
    ]
