# Generated by Django 5.0.1 on 2026-02-16 13:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('code', models.CharField(help_text='Ex: MATH, FR, ANG', max_length=10, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)], verbose_name='coefficient')),
                ('couleur', models.CharField(default='#3B82F6', help_text="Couleur hex pour l'emploi du temps, ex: #3B82F6", max_length=7, verbose_name='couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('niveau', models.CharField(choices=[('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2NDE', 'Seconde'), ('1ERE', 'Première'), ('TLE', 'Terminale')], max_length=10, verbose_name='niveau')),
                ('nom', models.CharField(help_text='Ex: 6ème A, Terminale S1', max_length=50, verbose_name='nom')),
                ('filiere', models.CharField(blank=True, help_text='Ex: Sciences, Lettres, TSE', max_length=50, verbose_name='filière')),
                ('capacite_max', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='capacité maximale')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='administration.anneescolaire', verbose_name='année scolaire')),
                ('professeur_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='authentication.enseignantprofile', verbose_name='professeur principal')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='administration.salle', verbose_name='salle')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['niveau', 'nom'],
                'unique_together': {('nom', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('periode', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('S1', '1er Semestre'), ('S2', '2ème Semestre')], max_length=5, verbose_name='période')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='moyenne générale')),
                ('rang', models.PositiveIntegerField(help_text='Classement dans la classe', verbose_name='rang')),
                ('total_eleves', models.PositiveIntegerField(help_text="Nombre total d'élèves dans la classe", verbose_name='total élèves')),
                ('appreciation_generale', models.TextField(verbose_name='appréciation générale')),
                ('appreciation_prof_principal', models.TextField(blank=True, verbose_name='appréciation professeur principal')),
                ('appreciation_directeur', models.TextField(blank=True, verbose_name='appréciation directeur')),
                ('total_absences', models.PositiveIntegerField(default=0, verbose_name='total absences')),
                ('total_retards', models.PositiveIntegerField(default=0, verbose_name='total retards')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='bulletins/%Y/%m/', verbose_name='fichier PDF')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='date de génération')),
                ('est_valide', models.BooleanField(default=False, verbose_name='validé')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='administration.anneescolaire', verbose_name='année scolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='authentication.eleveprofile', verbose_name='élève')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='pedagogie.classe', verbose_name='classe')),
            ],
            options={
                'verbose_name': 'bulletin',
                'verbose_name_plural': 'bulletins',
                'ordering': ['-annee_scolaire', '-periode', 'classe', 'rang'],
                'unique_together': {('eleve', 'periode', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi'), ('DIM', 'Dimanche')], max_length=3, verbose_name='jour')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploi_du_temps', to='pedagogie.classe', verbose_name='classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='authentication.enseignantprofile', verbose_name='enseignant')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='administration.salle', verbose_name='salle')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='pedagogie.matiere', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'créneau emploi du temps',
                'verbose_name_plural': 'emploi du temps',
                'ordering': ['jour', 'heure_debut'],
                'indexes': [models.Index(fields=['classe', 'jour'], name='pedagogie_e_classe__6d854c_idx'), models.Index(fields=['enseignant', 'jour'], name='pedagogie_e_enseign_08cd21_idx')],
                'unique_together': {('classe', 'jour', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('type_note', models.CharField(choices=[('DEVOIR', 'Devoir'), ('COMPOSITION', 'Composition'), ('INTERRO', 'Interrogation'), ('EXAMEN', 'Examen'), ('CONTROLE', 'Contrôle continu')], max_length=20, verbose_name='type de note')),
                ('periode', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('S1', '1er Semestre'), ('S2', '2ème Semestre')], max_length=5, verbose_name='période')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='note')),
                ('sur', models.DecimalField(decimal_places=2, default=20, help_text='Note maximale possible', max_digits=5, verbose_name='sur')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='coefficient')),
                ('appreciation', models.TextField(blank=True, verbose_name='appréciation')),
                ('date_evaluation', models.DateField(verbose_name="date d'évaluation")),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='administration.anneescolaire', verbose_name='année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pedagogie.classe', verbose_name='classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='authentication.eleveprofile', verbose_name='élève')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to='authentication.enseignantprofile', verbose_name='enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pedagogie.matiere', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-date_evaluation'],
                'indexes': [models.Index(fields=['eleve', 'periode', 'annee_scolaire'], name='pedagogie_n_eleve_i_9c77cd_idx'), models.Index(fields=['classe', 'matiere', 'periode'], name='pedagogie_n_classe__ad107f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('date', models.DateField(verbose_name='date')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard'), ('ABSENT_J', 'Absent justifié')], default='PRESENT', max_length=10, verbose_name='statut')),
                ('justification', models.TextField(blank=True, verbose_name='justification')),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='presences/justificatifs/%Y/%m/', verbose_name='document justificatif')),
                ('notification_envoyee', models.BooleanField(default=False, verbose_name='notification envoyée')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='pedagogie.classe', verbose_name='classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='authentication.eleveprofile', verbose_name='élève')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
                ('matiere', models.ForeignKey(blank=True, help_text='Laissez vide pour présence globale journée', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='pedagogie.matiere', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'présence',
                'verbose_name_plural': 'présences',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['eleve', 'date'], name='pedagogie_p_eleve_i_cfc756_idx'), models.Index(fields=['classe', 'date'], name='pedagogie_p_classe__42e04f_idx')],
                'unique_together': {('eleve', 'date', 'matiere')},
            },
        ),
    ]
