# Generated by Django 5.0.1 on 2026-02-16 13:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('matricule', models.CharField(help_text='Ex: 2026/001/EL', max_length=20, unique=True, verbose_name='matricule')),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='groupe sanguin')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies')),
                ('notes_medicales', models.TextField(blank=True, verbose_name='notes médicales')),
                ('contact_urgence_nom', models.CharField(max_length=200, verbose_name='contact urgence - nom')),
                ('contact_urgence_phone', models.CharField(max_length=20, verbose_name='contact urgence - téléphone')),
                ('contact_urgence_relation', models.CharField(help_text='Ex: Père, Mère, Tuteur', max_length=50, verbose_name='contact urgence - relation')),
                ('is_redoublant', models.BooleanField(default=False, verbose_name='redoublant')),
                ('date_admission', models.DateField(verbose_name="date d'admission")),
            ],
            options={
                'verbose_name': 'profil élève',
                'verbose_name_plural': 'profils élèves',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='EnseignantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('numero_cnss', models.CharField(blank=True, help_text='Numéro de sécurité sociale', max_length=50, verbose_name='numéro CNSS')),
                ('diplomes', models.TextField(blank=True, verbose_name='diplômes')),
                ('specialite', models.CharField(blank=True, max_length=100, verbose_name='spécialité')),
                ('is_professeur_principal', models.BooleanField(default=False, verbose_name='professeur principal')),
                ('date_embauche', models.DateField(verbose_name="date d'embauche")),
            ],
            options={
                'verbose_name': 'profil enseignant',
                'verbose_name_plural': 'profils enseignants',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('relation', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur légal'), ('AUTRE', 'Autre')], max_length=50, verbose_name='relation')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='profession')),
            ],
            options={
                'verbose_name': 'profil parent',
                'verbose_name_plural': 'profils parents',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('ENSEIGNANT', 'Enseignant'), ('ELEVE', 'Élève'), ('PARENT', 'Parent'), ('COMPTABLE', 'Comptable'), ('SURVEILLANT', 'Surveillant')], default='ELEVE', max_length=20, verbose_name='rôle')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/%Y/%m/', verbose_name='photo de profil')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('is_verified', models.BooleanField(default=False, verbose_name='compte vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5, verbose_name='langue préférée')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ComptableProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('numero_cnss', models.CharField(blank=True, max_length=50, verbose_name='numéro CNSS')),
                ('date_embauche', models.DateField(verbose_name="date d'embauche")),
                ('user', models.OneToOneField(limit_choices_to={'role': 'COMPTABLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='comptable_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil comptable',
                'verbose_name_plural': 'profils comptables',
            },
        ),
    ]
