# Generated by Django 5.0.1 on 2026-02-16 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleveprofile',
            name='classe_actuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='pedagogie.classe', verbose_name='classe actuelle'),
        ),
        migrations.AddField(
            model_name='eleveprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'ELEVE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eleve_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enseignantprofile',
            name='classe_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignant_principal', to='pedagogie.classe', verbose_name='classe principale'),
        ),
        migrations.AddField(
            model_name='enseignantprofile',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='pedagogie.matiere', verbose_name='matières enseignées'),
        ),
        migrations.AddField(
            model_name='enseignantprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='eleves',
            field=models.ManyToManyField(related_name='parents', to='authentication.eleveprofile', verbose_name='enfants'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='authenticat_email_d74434_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='authenticat_role_7fb088_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'role'], name='authenticat_is_acti_f5c1f7_idx'),
        ),
    ]
