# Generated by Django 5.0.1 on 2026-02-16 13:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('numero', models.CharField(help_text='Ex: FACT-2026-001', max_length=50, unique=True, verbose_name='numéro de facture')),
                ('lignes', models.JSONField(help_text='Liste des frais: [{"frais_id": 1, "designation": "...", "montant": 500000}, ...]', verbose_name='lignes de facture')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant total')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='montant payé')),
                ('montant_restant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='montant restant')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PARTIELLE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=15, verbose_name='statut')),
                ('date_emission', models.DateField(verbose_name="date d'émission")),
                ('date_echeance', models.DateField(verbose_name="date d'échéance")),
                ('remise_pourcentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='remise (%)')),
                ('remise_montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='remise (montant)')),
                ('motif_remise', models.CharField(blank=True, max_length=200, verbose_name='motif remise')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/%Y/%m/', verbose_name='facture PDF')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='administration.anneescolaire', verbose_name='année scolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='authentication.eleveprofile', verbose_name='élève')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='FraisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type_frais', models.CharField(choices=[('SCOLARITE', 'Frais de scolarité'), ('INSCRIPTION', "Frais d'inscription"), ('REINSCRIPTION', 'Frais de réinscription'), ('EXAMEN', "Frais d'examen"), ('TRANSPORT', 'Transport scolaire'), ('CANTINE', 'Cantine'), ('ACTIVITES', 'Activités extrascolaires'), ('TENUE', 'Tenue scolaire'), ('MATERIEL', 'Matériel pédagogique'), ('BIBLIO', 'Bibliothèque'), ('AUTRE', 'Autre')], max_length=20, verbose_name='type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant')),
                ('montant_par_niveau', models.JSONField(blank=True, help_text='Ex: {"6EME": 500000, "TLE": 750000}', null=True, verbose_name='montant par niveau')),
                ('est_payable_en_tranches', models.BooleanField(default=True, verbose_name='payable en tranches')),
                ('nombre_tranches', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='nombre de tranches')),
                ('date_limite_1ere_tranche', models.DateField(blank=True, null=True, verbose_name='date limite 1ère tranche')),
                ('date_limite_2eme_tranche', models.DateField(blank=True, null=True, verbose_name='date limite 2ème tranche')),
                ('date_limite_3eme_tranche', models.DateField(blank=True, null=True, verbose_name='date limite 3ème tranche')),
                ('is_obligatoire', models.BooleanField(default=True, verbose_name='obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_scolaires', to='administration.anneescolaire', verbose_name='année scolaire')),
            ],
            options={
                'verbose_name': 'frais scolaire',
                'verbose_name_plural': 'frais scolaires',
                'ordering': ['type_frais', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('numero_recu', models.CharField(help_text='Ex: RECU-2026-001', max_length=50, unique=True, verbose_name='numéro de reçu')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant payé')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE', 'Mobile Money'), ('ORANGE', 'Orange Money'), ('MTN', 'MTN Mobile Money'), ('CARTE', 'Carte bancaire')], max_length=15, verbose_name='mode de paiement')),
                ('reference_transaction', models.CharField(blank=True, help_text='Numéro de chèque, ID transaction mobile money, etc.', max_length=200, verbose_name='référence transaction')),
                ('numero_telephone', models.CharField(blank=True, help_text='Pour Mobile Money', max_length=20, verbose_name='numéro de téléphone')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='date de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=15, verbose_name='statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('fichier_recu_pdf', models.FileField(blank=True, null=True, upload_to='recus/%Y/%m/', verbose_name='reçu PDF')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='authentication.eleveprofile', verbose_name='élève')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finances.facture', verbose_name='facture')),
                ('recu_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_recus', to=settings.AUTH_USER_MODEL, verbose_name='reçu par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('type_rapport', models.CharField(choices=[('JOUR', 'Journalier'), ('SEMAINE', 'Hebdomadaire'), ('MOIS', 'Mensuel'), ('TRIMESTRE', 'Trimestriel'), ('ANNEE', 'Annuel')], max_length=15, verbose_name='type de rapport')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('total_factures_emises', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total factures émises')),
                ('total_paiements_recus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total paiements reçus')),
                ('total_impayés', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total impayés')),
                ('nombre_factures', models.PositiveIntegerField(default=0, verbose_name='nombre de factures')),
                ('nombre_paiements', models.PositiveIntegerField(default=0, verbose_name='nombre de paiements')),
                ('details_par_mode', models.JSONField(blank=True, help_text='Ex: {"ESPECES": 5000000, "MOBILE": 3000000}', null=True, verbose_name='détails par mode de paiement')),
                ('fichier_excel', models.FileField(blank=True, null=True, upload_to='rapports/financiers/%Y/%m/', verbose_name='rapport Excel')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/financiers/%Y/%m/', verbose_name='rapport PDF')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='date de génération')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_financiers', to='administration.anneescolaire', verbose_name='année scolaire')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL, verbose_name='généré par')),
            ],
            options={
                'verbose_name': 'rapport financier',
                'verbose_name_plural': 'rapports financiers',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='finances_fa_eleve_i_ddf2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut'], name='finances_fa_statut_80f85b_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['facture'], name='finances_pa_facture_a458d2_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['eleve', 'date_paiement'], name='finances_pa_eleve_i_7bf8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='finances_pa_statut_2025e6_idx'),
        ),
    ]
